# Generated by Django 5.2.8 on 2025-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_jobcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=50)),
            ],
        ),
    ]
