# Generated by Django 5.2.8 on 2025-11-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_qualification'),
        ('Guest', '0003_tbl_jobprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_content', models.CharField(max_length=50)),
                ('job_requriedage', models.CharField(max_length=50)),
                ('job_experience', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
                ('job_lastdate', models.DateField()),
                ('job_date', models.DateField(auto_now_add=True)),
                ('job_status', models.IntegerField(default=0)),
                ('jobcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_jobcategory')),
                ('jobprovider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_jobprovider')),
                ('jobtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_jobtype')),
            ],
        ),
    ]
