# Generated by Django 5.2.8 on 2025-11-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_job',
        ),
    ]
