# Generated by Django 5.2.8 on 2025-11-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_qualification'),
        ('JobProvider', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobqualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_job')),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_qualification')),
            ],
        ),
    ]
