# Generated by Django 5.2.8 on 2025-12-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0004_tbl_jobqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_details', models.CharField(max_length=50)),
                ('exam_todate', models.DateField()),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('exam_status', models.IntegerField(default=0)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_job')),
            ],
        ),
    ]
