# Generated by Django 5.2.8 on 2025-12-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0005_tbl_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50)),
                ('question_file', models.FileField(upload_to='Assets/QuestionDocs/')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_exam')),
            ],
        ),
    ]
