# Generated by Django 5.2.8 on 2025-12-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0006_tbl_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
                ('option_status', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_question')),
            ],
        ),
    ]
