# Generated by Django 5.2.8 on 2025-12-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0007_tbl_option'),
        ('User', '0005_remove_tbl_examhead_exam_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_question',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='tbl_option',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='tbl_exam',
        ),
        migrations.DeleteModel(
            name='tbl_option',
        ),
        migrations.DeleteModel(
            name='tbl_question',
        ),
    ]
