# Generated by Django 5.2.8 on 2025-12-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('JobProvider', '0008_remove_tbl_question_exam_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=50)),
                ('examination_mark', models.CharField(max_length=50)),
                ('examination_qno', models.CharField(max_length=50)),
                ('examination_time', models.CharField(max_length=50)),
                ('examination_status', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('jobprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_jobprovider')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_examination')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_questions')),
            ],
        ),
    ]
