# Generated by Django 5.2.8 on 2025-12-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0009_tbl_examination_tbl_questions_tbl_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examination',
            name='jobprovider',
        ),
        migrations.AddField(
            model_name='tbl_examination',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_job'),
        ),
    ]
