# Generated by Django 5.2.8 on 2025-12-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0010_remove_tbl_examination_jobprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examination',
            name='examination_qno',
        ),
    ]
