# Generated by Django 5.2.8 on 2025-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0011_remove_tbl_examination_examination_qno'),
        ('User', '0009_remove_tbl_examinationbody_examination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_questions',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='tbl_options',
            name='questions',
        ),
        migrations.DeleteModel(
            name='tbl_examination',
        ),
        migrations.DeleteModel(
            name='tbl_options',
        ),
        migrations.DeleteModel(
            name='tbl_questions',
        ),
    ]
