# Generated by Django 5.2.8 on 2025-12-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobProvider', '0013_tbl_examination_tbl_questions_tbl_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examination',
            name='examination_qno',
        ),
    ]
