# Generated by Django 5.2.8 on 2025-11-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_qualification'),
        ('Guest', '0002_alter_tbl_user_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobprovider_name', models.CharField(max_length=50)),
                ('jobprovider_email', models.CharField(max_length=50)),
                ('jobprovider_contact', models.CharField(max_length=50)),
                ('jobprovider_address', models.CharField(max_length=100)),
                ('jobprovider_photo', models.FileField(upload_to='Assets/JobProviderDocs/')),
                ('jobprovider_proof', models.FileField(upload_to='Assets/JobProviderDocs/')),
                ('jobprovider_status', models.IntegerField(default=0)),
                ('jobprovider_doj', models.DateField(auto_now_add=True)),
                ('jobprovider_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
