# Generated by Django 5.2.8 on 2025-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
