# Generated by Django 5.2.8 on 2025-12-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('JobProvider', '0004_tbl_jobqualification'),
        ('User', '0002_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_file', models.FileField(upload_to='Assets/RequestDocs/')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
