# Generated by Django 5.2.8 on 2025-12-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('JobProvider', '0007_tbl_option'),
        ('User', '0003_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examhead_date', models.DateField(auto_now_add=True)),
                ('examhead_status', models.IntegerField(default=0)),
                ('examhead_score', models.IntegerField(null=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_exam')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_exambody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exambody_status', models.IntegerField(default=0)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_question')),
                ('examhead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examhead')),
            ],
        ),
    ]
