# Generated by Django 5.2.8 on 2025-12-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_examhead_tbl_exambody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examhead',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='tbl_examhead',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_exambody',
        ),
        migrations.DeleteModel(
            name='tbl_examhead',
        ),
    ]
