# Generated by Django 5.2.8 on 2025-12-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('JobProvider', '0009_tbl_examination_tbl_questions_tbl_options'),
        ('User', '0005_remove_tbl_examhead_exam_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_examination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='JobProvider.tbl_options')),
                ('myanswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='JobProvider.tbl_options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_questions')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timmer', models.TimeField()),
                ('timmer_status', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobProvider.tbl_examination')),
            ],
        ),
    ]
