# Generated by Django 5.2.8 on 2025-12-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('User', '0006_tbl_examinationbody_tbl_examinationanswers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
                ('jobprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_jobprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
