# Generated by Django 5.2.8 on 2025-12-12 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_jobprovider'),
        ('User', '0007_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='jobprovider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_jobprovider'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
