# Generated by Django 5.2.8 on 2025-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_feedback_jobprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_timmer',
            name='exam',
        ),
        migrations.DeleteModel(
            name='tbl_examinationanswers',
        ),
        migrations.DeleteModel(
            name='tbl_examinationbody',
        ),
        migrations.DeleteModel(
            name='tbl_timmer',
        ),
    ]
